name: 'Linear Release Notes'
description: 'Collates release notes within Linear tickets'
author: 'Chris Conn'
inputs:
  github-token:
    description: 'Pass in secrets.GITHUB_TOKEN'
    required: true
  linear-token:
    description: 'Pass in secrets.LINEAR_TOKEN'
    required: true

runs:
  using: node12
  main: dist/index.js
